`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Module Name: Camera_Capture
//
// MODIFIED (2026-07-17): capture an already packetized 8-bit camera stream.
// - pclk is generated by the camera and is NOT the RTL processing clock.
// - sys_clk is the FPGA 100 MHz clock used by every register in this module.
// - Alarmer converts each observable pclk rising edge into one sys_clk pulse.
// - href rising/falling produces line_start/line_end without requiring VSYNC.
// - One href interval is expected to contain exactly 128 bytes, including the
//   existing 16-byte header and 2-byte CRC tail.
// - Only metadata needed by Byte_Replacer is generated here.  Header fields
//   already present in the camera stream are not rebuilt.
//////////////////////////////////////////////////////////////////////////////////
module Camera_Capture #(
    parameter [1:0]   CAM_ID          = 2'd0,
    parameter integer PACKET_BYTES    = 128,
    parameter integer LINES_PER_FRAME = 480
)(
    input  wire       pclk,
    input  wire       sys_clk,
    input  wire       rst,
    input  wire       href,
    input  wire [7:0] camera_data,

    output reg  [7:0] byte_data,
    output reg        byte_valid,
    output reg        line_start,
    output reg        line_end,
    output wire [1:0] line_cam_id,
    output reg  [7:0] line_flags,

    output wire [15:0] current_row_idx,
    output wire [8:0]  current_byte_count
);

    // MODIFIED: the four FPGA-generated flag bits occupy the low nibble.
    // Byte_Replacer ORs these bits into the row_flags byte already in the packet.
    localparam [7:0] PKT_ROW_FLAG_FIRST_ROW    = 8'h01;
    localparam [7:0] PKT_ROW_FLAG_LAST_ROW     = 8'h02;
    localparam [7:0] PKT_ROW_FLAG_FRAME_OVFLOW = 8'h04; // set by Line_Buffer
    localparam [7:0] PKT_ROW_FLAG_LENGTH_ERROR = 8'h08;

    wire pclk_pulse;

    (* ASYNC_REG = "TRUE" *) reg href_meta;
    (* ASYNC_REG = "TRUE" *) reg href_sync;
    reg href_sync_d;

    reg [15:0] row_idx;
    reg [8:0]  byte_count;

    wire href_rise = href_sync && !href_sync_d;
    wire href_fall = !href_sync && href_sync_d;

    assign line_cam_id       = CAM_ID;
    assign current_row_idx   = row_idx;
    assign current_byte_count = byte_count;

    Alarmer u_pclk_alarmer (
        .clk_data (pclk),
        .clk      (sys_clk),
        .rst      (rst),
        .alarm    (pclk_pulse)
    );

    // href is a separate asynchronous camera signal and therefore receives its
    // own two-stage synchronizer.  Edge detection occurs only in sys_clk domain.
    always @(posedge sys_clk or posedge rst) begin
        if (rst) begin
            href_meta   <= 1'b0;
            href_sync   <= 1'b0;
            href_sync_d <= 1'b0;
        end else begin
            href_meta   <= href;
            href_sync   <= href_meta;
            href_sync_d <= href_sync;
        end
    end

    // MODIFIED: simple byte counter and row counter replace the former nibble
    // assembly and formatter-oriented descriptor logic.
    always @(posedge sys_clk or posedge rst) begin
        if (rst) begin
            row_idx    <= 16'd0;
            byte_count <= 9'd0;
            byte_data  <= 8'd0;
            byte_valid <= 1'b0;
            line_start <= 1'b0;
            line_end   <= 1'b0;
            line_flags <= 8'd0;
        end else begin
            byte_valid <= 1'b0;
            line_start <= 1'b0;
            line_end   <= 1'b0;

            if (href_rise) begin
                line_start <= 1'b1;
                // If href and the synchronized pclk edge arrive together, the
                // first byte belongs to this new packet and must be counted.
                byte_count <= pclk_pulse ? 9'd1 : 9'd0;
            end else if (pclk_pulse && href_sync) begin
                // Saturation preserves an unambiguous length-error indication
                // even if a malformed href interval contains far too many bytes.
                if (byte_count != 9'h1ff)
                    byte_count <= byte_count + 1'b1;
            end

            if (pclk_pulse && href_sync) begin
                byte_data  <= camera_data;
                byte_valid <= 1'b1;
            end

            if (href_fall) begin
                line_end <= 1'b1;
                line_flags <= ((row_idx == 0)
                               ? PKT_ROW_FLAG_FIRST_ROW : 8'd0) |
                              ((row_idx == LINES_PER_FRAME - 1)
                               ? PKT_ROW_FLAG_LAST_ROW : 8'd0) |
                              ((byte_count == PACKET_BYTES)
                               ? 8'd0 : PKT_ROW_FLAG_LENGTH_ERROR);

                if (row_idx == LINES_PER_FRAME - 1)
                    row_idx <= 16'd0;
                else
                    row_idx <= row_idx + 1'b1;
            end
        end
    end

    // This constant is documented beside the other flags even though ownership
    // belongs to Line_Buffer, where an actual lack of storage can be observed.
    wire _unused_flag_definition = ^PKT_ROW_FLAG_FRAME_OVFLOW;

endmodule
