`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Module Name: Camera_Capture
//
// MODIFIED (2026-07-17): capture an already packetized 8-bit camera stream.
// - pclk is generated by the camera and is NOT the RTL processing clock.
// - sys_clk is the FPGA 100 MHz clock used by every register in this module.
// - A synchronized/debounced edge detector converts each observable pclk rise
//   into one sys_clk pulse and preserves the byte seen at that edge.
// - href starts a line; line_end waits for the final filtered pclk event.
// - One href interval is expected to contain exactly 128 bytes, including the
//   existing 16-byte header and 2-byte CRC tail.
// - Only metadata needed by Byte_Replacer is generated here.  Header fields
//   already present in the camera stream are not rebuilt.
//////////////////////////////////////////////////////////////////////////////////
module Camera_Capture #(
    parameter [1:0]   CAM_ID          = 2'd0, // 本实例固定相机编号
    parameter integer PACKET_BYTES    = 128,  // href 内期望的 pclk byte 数
    parameter integer LINES_PER_FRAME = 480,  // 无 VSYNC 时用于帧回卷
    // 1 compares the MCU-provided big-endian CRC tail against CRC-16/
    // CCITT-FALSE over offsets 0..PACKET_BYTES-3. A mismatch is reported in
    // FPGA status bit 0x10; packet bytes still continue to Byte_Replacer.
    parameter         INGRESS_CRC_ENABLE = 1'b1,
    // PCLK high qualification depth (>=2).  A byte requires this many
    // consecutive synchronized high samples, which rejects a one-sample high
    // glitch.  Hardware ILA showed that a real DATA transition can be bounded
    // by only one observable low sample, so low re-arm has an independent
    // threshold.  The physical phases must still be observable by the 100 MHz
    // sys_clk; this is a fabric-domain mitigation, not an asynchronous FIFO.
    parameter integer PCLK_FILTER_LEN     = 2,
    parameter integer PCLK_LOW_FILTER_LEN = 1
)(
    input  wire       pclk,        // Camera 异步像素时钟，送入同步/滤波前端
    input  wire       sys_clk,     // FPGA 100 MHz，模块内所有寄存器的时钟
    input  wire       rst,         // 高有效异步复位
    input  wire       capture_enable, // 同步请求；只在干净 HREF 边界启停
    input  wire       href,        // 高电平包围一个完整的 128-byte 行包
    input  wire [7:0] camera_data, // 在 camera pclk 上升沿有效的输入 byte

    output reg  [7:0] byte_data,   // sys_clk 域锁存后的 camera_data
    output reg        byte_valid,  // 每个可观察 pclk 上升沿产生一拍
    output reg        line_start,  // href 上升沿单周期脉冲：重置/预留 LB 写 slot
    output reg        line_end,    // href 下降沿单周期脉冲：提交 LB 写 slot
    output wire [1:0] line_cam_id, // 常量 CAM_ID，与行包 metadata 一起提交
    output reg  [7:0] line_flags,  // registered with line_end for Line_Buffer

    output wire [15:0] current_row_idx,       // 调试：当前行编号，0 起始
    output wire [15:0] current_byte_count,    // 调试：当前 href 已观察到的 byte 数
    output reg  [15:0] last_line_byte_count,  // href_fall 时锁存，供 ILA 读取
    output reg         length_error_pulse     // 与 LENGTH_ERROR 判定同拍的单周期脉冲
);

    // FPGA-generated status is separate from sender_row_flags at offset 9.
    // Byte_Replacer writes this diagnostic byte to wire offset 13.
    // ========================================================================
    // SHARED PROTOCOL FLAGS -- Capture 生成，Line_Buffer/Byte_Replacer 解释
    // ========================================================================
    localparam [7:0] FPGA_STATUS_FRAME_OVERFLOW = 8'h01;
    localparam [7:0] FPGA_STATUS_LENGTH_ERROR   = 8'h08;
    localparam [7:0] FPGA_STATUS_CRC_ERROR      = 8'h10;

    // Byte-serial CRC-16/CCITT-FALSE: poly 0x1021, init 0xFFFF, refin=false,
    // refout=false, xorout=0. This matches Byte_Replacer and the Python host.
    function [15:0] crc16_byte;
        input [15:0] crc_in;
        input [7:0]  data_in;
        integer bit_index;
        reg [15:0] crc_work;
        begin
            crc_work = crc_in ^ {data_in, 8'h00};
            for (bit_index = 0; bit_index < 8; bit_index = bit_index + 1) begin
                if (crc_work[15])
                    crc_work = {crc_work[14:0], 1'b0} ^ 16'h1021;
                else
                    crc_work = {crc_work[14:0], 1'b0};
            end
            crc16_byte = crc_work;
        end
    endfunction

    // ========================================================================
    // COHERENT ASYNC FRONT-END (MODIFIED 2026-07-24)
    // ------------------------------------------------------------------------
    // 旧实现里 pclk 经 Alarmer(2FF + 电平沿检测) 生成 strobe，href 经另一条独立
    // 2FF 同步，而 camera_data 在 strobe 拍“新鲜”采样(0FF)。三条路径延迟不一致，
    // 且对 async strobe 直接做电平沿检测无法抑制毛刺/亚稳态造成的重复脉冲——
    // 这正是行内多插入 1 字节 (byte_count 129/130、payload 自某 offset 起整体
    // 右移 1) 的来源：一次物理 pclk 沿被判成两拍 pclk_pulse。
    //
    // 现在 pclk / href / camera_data 走匹配延迟同步。PCLK 使用两阶段资格判定：
    // 低相位证据允许跨过一个短高毛刺累积；重新 armed 后，高相位仍必须连续达到
    // PCLK_FILTER_LEN 拍才产生 byte_valid。这样既不把短毛刺算作 byte，也不让
    // 短毛刺阻止下一次真实 PCLK 上升沿。
    //
    // 注意：这是 PCLK 固定在 D14(Pmod，非时钟专用脚)约束下的“织构内缓解”，不是
    // 根因根除。若 pclk 实测频率高于 ~25 MHz，或存在快于 sys_clk 周期的抖动，
    // 仍需把 pclk 移到时钟专用脚并改用 pclk 域组包 + 异步 FIFO 跨时钟域。
    // ========================================================================
    (* ASYNC_REG = "TRUE" *) reg       pclk_meta;
    (* ASYNC_REG = "TRUE" *) reg       pclk_sync;
    (* ASYNC_REG = "TRUE" *) reg       href_meta;
    (* ASYNC_REG = "TRUE" *) reg       href_sync;
    (* IOB = "TRUE" *) reg [7:0] data_meta;
    reg [7:0] data_sync;

    reg [PCLK_FILTER_LEN-1:0] pclk_hist;    // recent synchronized samples (ILA)
    reg                       pclk_level;   // qualified PCLK phase (ILA)
    reg                       pclk_sync_d;  // 未滤波同步电平的上一拍
    reg                       href_sync_d;  // href_sync 上一拍，用于 rise/fall
    (* MARK_DEBUG = "TRUE" *) reg pclk_phase_armed;
    (* MARK_DEBUG = "TRUE" *) reg [PCLK_FILTER_LEN-1:0] pclk_low_count;
    (* MARK_DEBUG = "TRUE" *) reg [PCLK_FILTER_LEN-1:0] pclk_high_count;
    // Diagnostic-only early snapshot.  This is intentionally kept for ILA so
    // hardware can compare the first synchronized view of DATA with the later
    // phase-qualified functional sample.  It must not feed byte_data: when the
    // RP2350A changes DATA close to PCLK, this early point can still contain
    // bits from the preceding byte.
    (* MARK_DEBUG = "TRUE" *) reg [7:0] data_on_pclk_rise;

    (* MARK_DEBUG = "TRUE" *)
    wire pclk_sync_rise = pclk_sync && !pclk_sync_d;

    // Phase-qualified byte event.  Low and high phases are intentionally
    // asymmetric: one observed low sample re-arms, while two consecutive high
    // samples are still required to emit a byte.  This accepts the attempt21
    // low-runt boundary but continues to reject its one-sample high glitches.
    (* MARK_DEBUG = "TRUE" *)
    wire pclk_pulse = pclk_phase_armed && pclk_sync &&
                      (pclk_high_count == PCLK_FILTER_LEN - 1);

    (* MARK_DEBUG = "TRUE" *)
    wire href_rise = href_sync && !href_sync_d; // 包开始事件
    (* MARK_DEBUG = "TRUE" *)
    wire href_fall = !href_sync && href_sync_d; // 包结束/行编号递增事件

    // ========================================================================
    // CAPTURE/ROW-ONLY REGISTERS -- 仅 byte/row 处理 always 写入
    // ========================================================================
    reg [15:0] row_idx;    // MCU 复位后默认从第 0 行开始；到上限自动回卷
    // 16 bit avoids hiding the true HREF length behind the former 9-bit
    // saturation value 511.  This counter does not alter the payload path.
    reg [15:0] byte_count;
    (* MARK_DEBUG = "TRUE" *) reg capture_armed;
    (* MARK_DEBUG = "TRUE" *) reg line_active;
    (* MARK_DEBUG = "TRUE" *) reg line_end_pending;

    // ========================================================================
    // INGRESS-CRC REGISTERS -- only the capture/row agent writes these
    // ========================================================================
    // ingress_crc accumulates bytes 0..125. ingress_received_crc captures the
    // MCU's big-endian bytes at offsets 126/127. Comparison is meaningful only
    // after a complete 128-byte row; malformed lengths are reported as 0x08.
    (* MARK_DEBUG = "TRUE" *) reg [15:0] ingress_crc;
    (* MARK_DEBUG = "TRUE" *) reg [15:0] ingress_received_crc;

    wire line_length_error = (byte_count != PACKET_BYTES);
    (* MARK_DEBUG = "TRUE" *)
    wire ingress_crc_error = (INGRESS_CRC_ENABLE != 0) &&
                             !line_length_error &&
                             (ingress_received_crc != ingress_crc);

    assign line_cam_id        = CAM_ID;
    assign current_row_idx    = row_idx;
    assign current_byte_count = byte_count;

    // pclk / href / camera_data 等深度同步 + pclk 去抖，全部在 sys_clk 域。
    always @(posedge sys_clk or posedge rst) begin
        if (rst) begin
            pclk_meta    <= 1'b0;
            pclk_sync    <= 1'b0;
            href_meta    <= 1'b0;
            href_sync    <= 1'b0;
            href_sync_d  <= 1'b0;
            data_meta    <= 8'd0;
            data_sync    <= 8'd0;
            pclk_hist    <= {PCLK_FILTER_LEN{1'b0}};
            pclk_level   <= 1'b0;
            pclk_sync_d  <= 1'b0;
            pclk_phase_armed <= 1'b0;
            pclk_low_count   <= {PCLK_FILTER_LEN{1'b0}};
            pclk_high_count  <= {PCLK_FILTER_LEN{1'b0}};
            data_on_pclk_rise <= 8'd0;
        end else begin
            pclk_meta <= pclk;        pclk_sync <= pclk_meta;
            href_meta <= href;        href_sync <= href_meta;
            data_meta <= camera_data; data_sync <= data_meta;
            href_sync_d <= href_sync;
            pclk_sync_d <= pclk_sync;

            // Preserve the earliest synchronized DATA view for ILA diagnosis.
            // The functional byte is sampled later, at pclk_pulse, after the
            // high phase has passed PCLK_FILTER_LEN consecutive observations.
            if (pclk_sync_rise)
                data_on_pclk_rise <= data_sync;

            // Keep the raw history for ILA correlation; functional edge
            // qualification is the two-phase state below.
            pclk_hist <= {pclk_hist[PCLK_FILTER_LEN-2:0], pclk_sync};

            if (pclk_phase_armed) begin
                pclk_low_count <= {PCLK_FILTER_LEN{1'b0}};
                if (!pclk_sync) begin
                    pclk_high_count <= {PCLK_FILTER_LEN{1'b0}};
                end else if (pclk_high_count == PCLK_FILTER_LEN - 1) begin
                    pclk_phase_armed <= 1'b0;
                    pclk_high_count  <= {PCLK_FILTER_LEN{1'b0}};
                    pclk_level       <= 1'b1;
                end else begin
                    pclk_high_count <= pclk_high_count + 1'b1;
                end
            end else begin
                pclk_high_count <= {PCLK_FILTER_LEN{1'b0}};
                if (!pclk_sync) begin
                    if (pclk_low_count == PCLK_LOW_FILTER_LEN - 1) begin
                        pclk_phase_armed <= 1'b1;
                        pclk_low_count   <= {PCLK_FILTER_LEN{1'b0}};
                        pclk_level       <= 1'b0;
                    end else begin
                        pclk_low_count <= pclk_low_count + 1'b1;
                    end
                end
                // A short high runt while waiting for low phase does not erase
                // already accumulated low evidence.  It also cannot emit a
                // byte because pclk_phase_armed is still low.
            end
        end
    end

    // MODIFIED: simple byte counter and row counter replace the former nibble
    // assembly and formatter-oriented descriptor logic.
    always @(posedge sys_clk or posedge rst) begin
        if (rst) begin
            row_idx    <= 16'd0;
            byte_count <= 16'd0;
            byte_data  <= 8'd0;
            byte_valid <= 1'b0;
            line_start <= 1'b0;
            line_end   <= 1'b0;
            line_flags <= 8'd0;
            last_line_byte_count <= 16'd0;
            length_error_pulse    <= 1'b0;
            capture_armed          <= 1'b0;
            line_active            <= 1'b0;
            line_end_pending       <= 1'b0;
            ingress_crc            <= 16'hFFFF;
            ingress_received_crc   <= 16'd0;
        end else begin
            // 三个输出均为事件脉冲，默认每拍清零，仅在下方条件中拉高。
            byte_valid <= 1'b0;
            line_start <= 1'b0;
            line_end   <= 1'b0;
            length_error_pulse <= 1'b0;

            // SW15 is a capture request, not a pipeline reset.  Enabling while
            // HREF is high waits for the next low interval.  Disabling during a
            // line lets that line finish and prevents the next line from
            // starting.  Downstream Line_Buffer/FIFO contents are not cleared.
            if (!line_active && !line_end_pending) begin
                if (!capture_enable)
                    capture_armed <= 1'b0;
                else if (!href_sync)
                    capture_armed <= 1'b1;
            end

            if (href_rise) begin
                if (capture_armed && capture_enable) begin
                    line_start <= 1'b1;
                    line_active <= 1'b1;
                    byte_count <= 16'd0;
                    ingress_crc <= 16'hFFFF;
                    ingress_received_crc <= 16'd0;
                end
            end else if (pclk_pulse && line_active) begin
                // Saturation preserves an unambiguous length-error indication
                // even if a malformed href interval contains far too many bytes.
                if (byte_count != 16'hffff)
                    byte_count <= byte_count + 1'b1;
            end

            if (pclk_pulse && line_active) begin
                // Use the phase-qualified sample, not data_on_pclk_rise.  The
                // attempt18..20 captures showed that a zero-valued header byte
                // inherited high bits from its immediately preceding byte.
                // Waiting until the qualified high phase gives DATA two extra
                // sys_clk observations to settle while preserving one output
                // event per accepted PCLK cycle.
                byte_data  <= data_sync;
                byte_valid <= 1'b1;

                // byte_count is the current zero-based wire offset before its
                // nonblocking increment. The final two bytes are the received
                // CRC and therefore never feed the calculation itself.
                if (INGRESS_CRC_ENABLE != 0) begin
                    if (byte_count < PACKET_BYTES - 2)
                        ingress_crc <= crc16_byte(ingress_crc, data_sync);
                    else if (byte_count == PACKET_BYTES - 2)
                        ingress_received_crc[15:8] <= data_sync;
                    else if (byte_count == PACKET_BYTES - 1)
                        ingress_received_crc[7:0] <= data_sync;
                end
            end

            // HREF has less qualification latency than pclk_pulse.  Do not
            // commit on href_fall until the final accepted PCLK has completed
            // and the phase qualifier has re-armed in the low phase.
            if (href_fall && line_active)
                line_end_pending <= 1'b1;

            if (line_end_pending && pclk_phase_armed && !pclk_sync) begin
                line_end <= 1'b1;
                line_active <= 1'b0;
                line_end_pending <= 1'b0;
                if (!capture_enable)
                    capture_armed <= 1'b0;
                last_line_byte_count <= byte_count;
                length_error_pulse <= (byte_count != PACKET_BYTES);
                // line_end and line_flags are registered together. Line_Buffer
                // observes both on the following sys_clk edge, so the status
                // belongs to this row without a separate commit state flag.
                line_flags <=
                    (line_length_error ? FPGA_STATUS_LENGTH_ERROR : 8'd0) |
                    (ingress_crc_error ? FPGA_STATUS_CRC_ERROR : 8'd0);
                // MODIFIED (2026-07-24): FPGA 侧不再自行生成 FIRST_ROW/LAST_ROW。
                // 那份内部 row_idx 计数器与真实帧边界不同步（每帧固定在
                // row_idx=2/75/76 附近产生错误标志）；真实的 FIRST_LINE/FINAL_LINE
                // 已由 RP2350A 固件 packet_generator() 正确写入包内 offset 9。
                // Byte_Replacer 保持 offset 9 原样，并把此状态独立写入 offset 13。
                // row_idx 仅保留用于 current_row_idx 调试输出与无 VSYNC 帧回卷；
                // 不再参与 line_flags。
                if (row_idx == LINES_PER_FRAME - 1)
                    row_idx <= 16'd0;
                else
                    row_idx <= row_idx + 1'b1;
            end
        end
    end

    // FRAME_OVERFLOW is asserted later by Line_Buffer. Camera_Capture owns the
    // length and ingress-CRC bits; Byte_Replacer writes their ORed status to
    // offset 13 and recalculates the packet's independent egress CRC.

endmodule
